// flow-typed signature: 6be0ca8bbd2b1c7d2b59427471fff586
// flow-typed version: <<STUB>>/bourbon_v^4.2.7/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bourbon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bourbon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bourbon/eyeglass-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bourbon/eyeglass-exports.js' {
  declare module.exports: $Exports<'bourbon/eyeglass-exports'>;
}
declare module 'bourbon/index' {
  declare module.exports: $Exports<'bourbon'>;
}
declare module 'bourbon/index.js' {
  declare module.exports: $Exports<'bourbon'>;
}
