// flow-typed signature: d53da799189dae47a93ac85de6cc8c2d
// flow-typed version: <<STUB>>/contentful_v^4.6.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contentful'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contentful' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contentful/dist/contentful' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.min' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.node' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.node.min' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/contentful' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/create-contentful-api' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/create-link-resolver' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/entities/asset' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/entities/content-type' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/entities/entry' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/entities/index' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/entities/space' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/mixins/link-getters' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/mixins/stringify-safe' {
  declare module.exports: any;
}

declare module 'contentful/dist/es6-modules/paged-sync' {
  declare module.exports: any;
}

declare module 'contentful/dist/version' {
  declare module.exports: any;
}

declare module 'contentful/tonic-example' {
  declare module.exports: any;
}

declare module 'contentful/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contentful/dist/contentful.js' {
  declare module.exports: $Exports<'contentful/dist/contentful'>;
}
declare module 'contentful/dist/contentful.min.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.min'>;
}
declare module 'contentful/dist/contentful.node.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.node'>;
}
declare module 'contentful/dist/contentful.node.min.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.node.min'>;
}
declare module 'contentful/dist/es6-modules/contentful.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/contentful'>;
}
declare module 'contentful/dist/es6-modules/create-contentful-api.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/create-contentful-api'>;
}
declare module 'contentful/dist/es6-modules/create-link-resolver.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/create-link-resolver'>;
}
declare module 'contentful/dist/es6-modules/entities/asset.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/entities/asset'>;
}
declare module 'contentful/dist/es6-modules/entities/content-type.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/entities/content-type'>;
}
declare module 'contentful/dist/es6-modules/entities/entry.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/entities/entry'>;
}
declare module 'contentful/dist/es6-modules/entities/index.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/entities/index'>;
}
declare module 'contentful/dist/es6-modules/entities/space.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/entities/space'>;
}
declare module 'contentful/dist/es6-modules/mixins/link-getters.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/mixins/link-getters'>;
}
declare module 'contentful/dist/es6-modules/mixins/stringify-safe.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/mixins/stringify-safe'>;
}
declare module 'contentful/dist/es6-modules/paged-sync.js' {
  declare module.exports: $Exports<'contentful/dist/es6-modules/paged-sync'>;
}
declare module 'contentful/dist/version.js' {
  declare module.exports: $Exports<'contentful/dist/version'>;
}
declare module 'contentful/tonic-example.js' {
  declare module.exports: $Exports<'contentful/tonic-example'>;
}
declare module 'contentful/version.js' {
  declare module.exports: $Exports<'contentful/version'>;
}
