// flow-typed signature: 232cd0bb6776dffc03071998cd8af175
// flow-typed version: <<STUB>>/express-sitemap_v^1.8.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-sitemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-sitemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-sitemap/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-sitemap/index' {
  declare module.exports: $Exports<'express-sitemap'>;
}
declare module 'express-sitemap/index.js' {
  declare module.exports: $Exports<'express-sitemap'>;
}
declare module 'express-sitemap/index.min.js' {
  declare module.exports: $Exports<'express-sitemap/index.min'>;
}
