// flow-typed signature: a2ba3683a8fd7c1b8454cebb81682d78
// flow-typed version: <<STUB>>/express-minify-html_v^0.11.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-minify-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-minify-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-minify-html/minifier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-minify-html/minifier.js' {
  declare module.exports: $Exports<'express-minify-html/minifier'>;
}
