// flow-typed signature: fa714afdc4eedb9bccf68efc7b6d2f41
// flow-typed version: <<STUB>>/express-subdomain_v^1.0.5/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-subdomain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-subdomain' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-subdomain/test/complex' {
  declare module.exports: any;
}

declare module 'express-subdomain/test/composable-middleware' {
  declare module.exports: any;
}

declare module 'express-subdomain/test/multi-level' {
  declare module.exports: any;
}

declare module 'express-subdomain/test/multi-tld' {
  declare module.exports: any;
}

declare module 'express-subdomain/test/simple' {
  declare module.exports: any;
}

declare module 'express-subdomain/test/static-files' {
  declare module.exports: any;
}

declare module 'express-subdomain/test/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-subdomain/index' {
  declare module.exports: $Exports<'express-subdomain'>;
}
declare module 'express-subdomain/index.js' {
  declare module.exports: $Exports<'express-subdomain'>;
}
declare module 'express-subdomain/test/complex.js' {
  declare module.exports: $Exports<'express-subdomain/test/complex'>;
}
declare module 'express-subdomain/test/composable-middleware.js' {
  declare module.exports: $Exports<'express-subdomain/test/composable-middleware'>;
}
declare module 'express-subdomain/test/multi-level.js' {
  declare module.exports: $Exports<'express-subdomain/test/multi-level'>;
}
declare module 'express-subdomain/test/multi-tld.js' {
  declare module.exports: $Exports<'express-subdomain/test/multi-tld'>;
}
declare module 'express-subdomain/test/simple.js' {
  declare module.exports: $Exports<'express-subdomain/test/simple'>;
}
declare module 'express-subdomain/test/static-files.js' {
  declare module.exports: $Exports<'express-subdomain/test/static-files'>;
}
declare module 'express-subdomain/test/validate.js' {
  declare module.exports: $Exports<'express-subdomain/test/validate'>;
}
