// flow-typed signature: 1f43ee37298f2b73c8f82687f5206491
// flow-typed version: <<STUB>>/express-enforces-ssl_v^1.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-enforces-ssl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-enforces-ssl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-enforces-ssl/index' {
  declare module.exports: $Exports<'express-enforces-ssl'>;
}
declare module 'express-enforces-ssl/index.js' {
  declare module.exports: $Exports<'express-enforces-ssl'>;
}
