// flow-typed signature: 9a48f7f45a626558b07517ab739a5665
// flow-typed version: <<STUB>>/eyeglass_v^0.8.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eyeglass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eyeglass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eyeglass/build/coverage' {
  declare module.exports: any;
}

declare module 'eyeglass/build/lint' {
  declare module.exports: any;
}

declare module 'eyeglass/build/site' {
  declare module.exports: any;
}

declare module 'eyeglass/build/test' {
  declare module.exports: any;
}

declare module 'eyeglass/Gruntfile' {
  declare module.exports: any;
}

declare module 'eyeglass/gulpfile' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/assets_importer' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/assets' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/function_loader' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/functions' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/functions/asset_url' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/functions/version' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/import_utils' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/index' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/module_importer' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/options' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/semver_checker' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/debug' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/deprecator' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/eyeglass_module' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/eyeglass_modules' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/files' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/NameExpander' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/package' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/resolve' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/sync_fn' {
  declare module.exports: any;
}

declare module 'eyeglass/lib/util/unquote' {
  declare module.exports: any;
}

declare module 'eyeglass/site/scripts/default' {
  declare module.exports: any;
}

declare module 'eyeglass/test/capture' {
  declare module.exports: any;
}

declare module 'eyeglass/test/fixtures/EyeglassModules/invalid_module_name/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'eyeglass/test/fixtures/has_a_main_already/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'eyeglass/test/fixtures/has_a_main_already/main' {
  declare module.exports: any;
}

declare module 'eyeglass/test/fixtures/is_a_module/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'eyeglass/test/fixtures/no_main_if_not_module/main' {
  declare module.exports: any;
}

declare module 'eyeglass/test/fixtures/simple_module_with_main/main' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_assets' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_deprecate' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_function_loading' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_imports' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_modules' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_NameExpander' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_options' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_sass_indented' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_semver' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_sync' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_utils' {
  declare module.exports: any;
}

declare module 'eyeglass/test/test_version' {
  declare module.exports: any;
}

declare module 'eyeglass/test/testutils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eyeglass/build/coverage.js' {
  declare module.exports: $Exports<'eyeglass/build/coverage'>;
}
declare module 'eyeglass/build/lint.js' {
  declare module.exports: $Exports<'eyeglass/build/lint'>;
}
declare module 'eyeglass/build/site.js' {
  declare module.exports: $Exports<'eyeglass/build/site'>;
}
declare module 'eyeglass/build/test.js' {
  declare module.exports: $Exports<'eyeglass/build/test'>;
}
declare module 'eyeglass/Gruntfile.js' {
  declare module.exports: $Exports<'eyeglass/Gruntfile'>;
}
declare module 'eyeglass/gulpfile.js' {
  declare module.exports: $Exports<'eyeglass/gulpfile'>;
}
declare module 'eyeglass/lib/assets_importer.js' {
  declare module.exports: $Exports<'eyeglass/lib/assets_importer'>;
}
declare module 'eyeglass/lib/assets.js' {
  declare module.exports: $Exports<'eyeglass/lib/assets'>;
}
declare module 'eyeglass/lib/eyeglass-exports.js' {
  declare module.exports: $Exports<'eyeglass/lib/eyeglass-exports'>;
}
declare module 'eyeglass/lib/function_loader.js' {
  declare module.exports: $Exports<'eyeglass/lib/function_loader'>;
}
declare module 'eyeglass/lib/functions.js' {
  declare module.exports: $Exports<'eyeglass/lib/functions'>;
}
declare module 'eyeglass/lib/functions/asset_url.js' {
  declare module.exports: $Exports<'eyeglass/lib/functions/asset_url'>;
}
declare module 'eyeglass/lib/functions/version.js' {
  declare module.exports: $Exports<'eyeglass/lib/functions/version'>;
}
declare module 'eyeglass/lib/import_utils.js' {
  declare module.exports: $Exports<'eyeglass/lib/import_utils'>;
}
declare module 'eyeglass/lib/index.js' {
  declare module.exports: $Exports<'eyeglass/lib/index'>;
}
declare module 'eyeglass/lib/module_importer.js' {
  declare module.exports: $Exports<'eyeglass/lib/module_importer'>;
}
declare module 'eyeglass/lib/options.js' {
  declare module.exports: $Exports<'eyeglass/lib/options'>;
}
declare module 'eyeglass/lib/semver_checker.js' {
  declare module.exports: $Exports<'eyeglass/lib/semver_checker'>;
}
declare module 'eyeglass/lib/util/debug.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/debug'>;
}
declare module 'eyeglass/lib/util/deprecator.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/deprecator'>;
}
declare module 'eyeglass/lib/util/eyeglass_module.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/eyeglass_module'>;
}
declare module 'eyeglass/lib/util/eyeglass_modules.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/eyeglass_modules'>;
}
declare module 'eyeglass/lib/util/files.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/files'>;
}
declare module 'eyeglass/lib/util/NameExpander.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/NameExpander'>;
}
declare module 'eyeglass/lib/util/package.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/package'>;
}
declare module 'eyeglass/lib/util/resolve.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/resolve'>;
}
declare module 'eyeglass/lib/util/sync_fn.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/sync_fn'>;
}
declare module 'eyeglass/lib/util/unquote.js' {
  declare module.exports: $Exports<'eyeglass/lib/util/unquote'>;
}
declare module 'eyeglass/site/scripts/default.js' {
  declare module.exports: $Exports<'eyeglass/site/scripts/default'>;
}
declare module 'eyeglass/test/capture.js' {
  declare module.exports: $Exports<'eyeglass/test/capture'>;
}
declare module 'eyeglass/test/fixtures/EyeglassModules/invalid_module_name/eyeglass-exports.js' {
  declare module.exports: $Exports<'eyeglass/test/fixtures/EyeglassModules/invalid_module_name/eyeglass-exports'>;
}
declare module 'eyeglass/test/fixtures/has_a_main_already/eyeglass-exports.js' {
  declare module.exports: $Exports<'eyeglass/test/fixtures/has_a_main_already/eyeglass-exports'>;
}
declare module 'eyeglass/test/fixtures/has_a_main_already/main.js' {
  declare module.exports: $Exports<'eyeglass/test/fixtures/has_a_main_already/main'>;
}
declare module 'eyeglass/test/fixtures/is_a_module/eyeglass-exports.js' {
  declare module.exports: $Exports<'eyeglass/test/fixtures/is_a_module/eyeglass-exports'>;
}
declare module 'eyeglass/test/fixtures/no_main_if_not_module/main.js' {
  declare module.exports: $Exports<'eyeglass/test/fixtures/no_main_if_not_module/main'>;
}
declare module 'eyeglass/test/fixtures/simple_module_with_main/main.js' {
  declare module.exports: $Exports<'eyeglass/test/fixtures/simple_module_with_main/main'>;
}
declare module 'eyeglass/test/test_assets.js' {
  declare module.exports: $Exports<'eyeglass/test/test_assets'>;
}
declare module 'eyeglass/test/test_deprecate.js' {
  declare module.exports: $Exports<'eyeglass/test/test_deprecate'>;
}
declare module 'eyeglass/test/test_function_loading.js' {
  declare module.exports: $Exports<'eyeglass/test/test_function_loading'>;
}
declare module 'eyeglass/test/test_imports.js' {
  declare module.exports: $Exports<'eyeglass/test/test_imports'>;
}
declare module 'eyeglass/test/test_modules.js' {
  declare module.exports: $Exports<'eyeglass/test/test_modules'>;
}
declare module 'eyeglass/test/test_NameExpander.js' {
  declare module.exports: $Exports<'eyeglass/test/test_NameExpander'>;
}
declare module 'eyeglass/test/test_options.js' {
  declare module.exports: $Exports<'eyeglass/test/test_options'>;
}
declare module 'eyeglass/test/test_sass_indented.js' {
  declare module.exports: $Exports<'eyeglass/test/test_sass_indented'>;
}
declare module 'eyeglass/test/test_semver.js' {
  declare module.exports: $Exports<'eyeglass/test/test_semver'>;
}
declare module 'eyeglass/test/test_sync.js' {
  declare module.exports: $Exports<'eyeglass/test/test_sync'>;
}
declare module 'eyeglass/test/test_utils.js' {
  declare module.exports: $Exports<'eyeglass/test/test_utils'>;
}
declare module 'eyeglass/test/test_version.js' {
  declare module.exports: $Exports<'eyeglass/test/test_version'>;
}
declare module 'eyeglass/test/testutils.js' {
  declare module.exports: $Exports<'eyeglass/test/testutils'>;
}
