// flow-typed signature: 05aad47928ec56731b761d4ccffc16a8
// flow-typed version: <<STUB>>/fs_v0.0.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fs/index' {
  declare module.exports: $Exports<'fs'>;
}
declare module 'fs/index.js' {
  declare module.exports: $Exports<'fs'>;
}
