// flow-typed signature: 6d264662202b72bd51a1fa90cddef572
// flow-typed version: <<STUB>>/highcharts_v^5.0.10/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highcharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'highcharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highcharts/adapters/standalone-framework' {
  declare module.exports: any;
}

declare module 'highcharts/adapters/standalone-framework.src' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-3d' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-3d.src' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-more' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-more.src' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts.src' {
  declare module.exports: any;
}

declare module 'highcharts/highmaps' {
  declare module.exports: any;
}

declare module 'highcharts/highmaps.src' {
  declare module.exports: any;
}

declare module 'highcharts/highstock' {
  declare module.exports: any;
}

declare module 'highcharts/highstock.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/highcharts-3d' {
  declare module.exports: any;
}

declare module 'highcharts/js/highcharts-3d.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/highcharts-more' {
  declare module.exports: any;
}

declare module 'highcharts/js/highcharts-more.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/highcharts' {
  declare module.exports: any;
}

declare module 'highcharts/js/highcharts.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/highmaps' {
  declare module.exports: any;
}

declare module 'highcharts/js/highmaps.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/highstock' {
  declare module.exports: any;
}

declare module 'highcharts/js/highstock.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/accessibility' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/accessibility.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/annotations' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/annotations.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/boost-canvas' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/boost-canvas.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/boost' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/boost.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/broken-axis' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/broken-axis.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/data' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/data.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/drilldown' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/drilldown.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/exporting' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/exporting.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/funnel' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/funnel.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/gantt' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/gantt.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/grid-axis' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/grid-axis.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/heatmap' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/heatmap.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/map' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/map.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/no-data-to-display' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/no-data-to-display.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/offline-exporting' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/offline-exporting.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/overlapping-datalabels' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/overlapping-datalabels.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/series-label' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/series-label.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/solid-gauge' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/solid-gauge.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/static-scale' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/static-scale.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/stock' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/stock.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/treemap' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/treemap.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/xrange-series' {
  declare module.exports: any;
}

declare module 'highcharts/js/modules/xrange-series.src' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/dark-blue' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/dark-green' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/dark-unica' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/gray' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/grid-light' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/grid' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/sand-signika' {
  declare module.exports: any;
}

declare module 'highcharts/js/themes/skies' {
  declare module.exports: any;
}

declare module 'highcharts/lib/canvg' {
  declare module.exports: any;
}

declare module 'highcharts/lib/canvg.src' {
  declare module.exports: any;
}

declare module 'highcharts/lib/jspdf' {
  declare module.exports: any;
}

declare module 'highcharts/lib/jspdf.src' {
  declare module.exports: any;
}

declare module 'highcharts/lib/rgbcolor' {
  declare module.exports: any;
}

declare module 'highcharts/lib/rgbcolor.src' {
  declare module.exports: any;
}

declare module 'highcharts/lib/svg2pdf' {
  declare module.exports: any;
}

declare module 'highcharts/lib/svg2pdf.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/accessibility' {
  declare module.exports: any;
}

declare module 'highcharts/modules/accessibility.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/annotations' {
  declare module.exports: any;
}

declare module 'highcharts/modules/annotations.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/boost-canvas' {
  declare module.exports: any;
}

declare module 'highcharts/modules/boost-canvas.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/boost' {
  declare module.exports: any;
}

declare module 'highcharts/modules/boost.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/broken-axis' {
  declare module.exports: any;
}

declare module 'highcharts/modules/broken-axis.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/canvas-tools' {
  declare module.exports: any;
}

declare module 'highcharts/modules/canvas-tools.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/data' {
  declare module.exports: any;
}

declare module 'highcharts/modules/data.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/drilldown' {
  declare module.exports: any;
}

declare module 'highcharts/modules/drilldown.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/exporting' {
  declare module.exports: any;
}

declare module 'highcharts/modules/exporting.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/funnel' {
  declare module.exports: any;
}

declare module 'highcharts/modules/funnel.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/gantt' {
  declare module.exports: any;
}

declare module 'highcharts/modules/gantt.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/grid-axis' {
  declare module.exports: any;
}

declare module 'highcharts/modules/grid-axis.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/heatmap' {
  declare module.exports: any;
}

declare module 'highcharts/modules/heatmap.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/map' {
  declare module.exports: any;
}

declare module 'highcharts/modules/map.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/no-data-to-display' {
  declare module.exports: any;
}

declare module 'highcharts/modules/no-data-to-display.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/offline-exporting' {
  declare module.exports: any;
}

declare module 'highcharts/modules/offline-exporting.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/overlapping-datalabels' {
  declare module.exports: any;
}

declare module 'highcharts/modules/overlapping-datalabels.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/series-label' {
  declare module.exports: any;
}

declare module 'highcharts/modules/series-label.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/solid-gauge' {
  declare module.exports: any;
}

declare module 'highcharts/modules/solid-gauge.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/static-scale' {
  declare module.exports: any;
}

declare module 'highcharts/modules/static-scale.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/stock' {
  declare module.exports: any;
}

declare module 'highcharts/modules/stock.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/treemap' {
  declare module.exports: any;
}

declare module 'highcharts/modules/treemap.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/xrange-series' {
  declare module.exports: any;
}

declare module 'highcharts/modules/xrange-series.src' {
  declare module.exports: any;
}

declare module 'highcharts/themes/dark-blue' {
  declare module.exports: any;
}

declare module 'highcharts/themes/dark-green' {
  declare module.exports: any;
}

declare module 'highcharts/themes/dark-unica' {
  declare module.exports: any;
}

declare module 'highcharts/themes/gray' {
  declare module.exports: any;
}

declare module 'highcharts/themes/grid-light' {
  declare module.exports: any;
}

declare module 'highcharts/themes/grid' {
  declare module.exports: any;
}

declare module 'highcharts/themes/sand-signika' {
  declare module.exports: any;
}

declare module 'highcharts/themes/skies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highcharts/adapters/standalone-framework.js' {
  declare module.exports: $Exports<'highcharts/adapters/standalone-framework'>;
}
declare module 'highcharts/adapters/standalone-framework.src.js' {
  declare module.exports: $Exports<'highcharts/adapters/standalone-framework.src'>;
}
declare module 'highcharts/highcharts-3d.js' {
  declare module.exports: $Exports<'highcharts/highcharts-3d'>;
}
declare module 'highcharts/highcharts-3d.src.js' {
  declare module.exports: $Exports<'highcharts/highcharts-3d.src'>;
}
declare module 'highcharts/highcharts-more.js' {
  declare module.exports: $Exports<'highcharts/highcharts-more'>;
}
declare module 'highcharts/highcharts-more.src.js' {
  declare module.exports: $Exports<'highcharts/highcharts-more.src'>;
}
declare module 'highcharts/highcharts.js' {
  declare module.exports: $Exports<'highcharts/highcharts'>;
}
declare module 'highcharts/highcharts.src.js' {
  declare module.exports: $Exports<'highcharts/highcharts.src'>;
}
declare module 'highcharts/highmaps.js' {
  declare module.exports: $Exports<'highcharts/highmaps'>;
}
declare module 'highcharts/highmaps.src.js' {
  declare module.exports: $Exports<'highcharts/highmaps.src'>;
}
declare module 'highcharts/highstock.js' {
  declare module.exports: $Exports<'highcharts/highstock'>;
}
declare module 'highcharts/highstock.src.js' {
  declare module.exports: $Exports<'highcharts/highstock.src'>;
}
declare module 'highcharts/js/highcharts-3d.js' {
  declare module.exports: $Exports<'highcharts/js/highcharts-3d'>;
}
declare module 'highcharts/js/highcharts-3d.src.js' {
  declare module.exports: $Exports<'highcharts/js/highcharts-3d.src'>;
}
declare module 'highcharts/js/highcharts-more.js' {
  declare module.exports: $Exports<'highcharts/js/highcharts-more'>;
}
declare module 'highcharts/js/highcharts-more.src.js' {
  declare module.exports: $Exports<'highcharts/js/highcharts-more.src'>;
}
declare module 'highcharts/js/highcharts.js' {
  declare module.exports: $Exports<'highcharts/js/highcharts'>;
}
declare module 'highcharts/js/highcharts.src.js' {
  declare module.exports: $Exports<'highcharts/js/highcharts.src'>;
}
declare module 'highcharts/js/highmaps.js' {
  declare module.exports: $Exports<'highcharts/js/highmaps'>;
}
declare module 'highcharts/js/highmaps.src.js' {
  declare module.exports: $Exports<'highcharts/js/highmaps.src'>;
}
declare module 'highcharts/js/highstock.js' {
  declare module.exports: $Exports<'highcharts/js/highstock'>;
}
declare module 'highcharts/js/highstock.src.js' {
  declare module.exports: $Exports<'highcharts/js/highstock.src'>;
}
declare module 'highcharts/js/modules/accessibility.js' {
  declare module.exports: $Exports<'highcharts/js/modules/accessibility'>;
}
declare module 'highcharts/js/modules/accessibility.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/accessibility.src'>;
}
declare module 'highcharts/js/modules/annotations.js' {
  declare module.exports: $Exports<'highcharts/js/modules/annotations'>;
}
declare module 'highcharts/js/modules/annotations.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/annotations.src'>;
}
declare module 'highcharts/js/modules/boost-canvas.js' {
  declare module.exports: $Exports<'highcharts/js/modules/boost-canvas'>;
}
declare module 'highcharts/js/modules/boost-canvas.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/boost-canvas.src'>;
}
declare module 'highcharts/js/modules/boost.js' {
  declare module.exports: $Exports<'highcharts/js/modules/boost'>;
}
declare module 'highcharts/js/modules/boost.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/boost.src'>;
}
declare module 'highcharts/js/modules/broken-axis.js' {
  declare module.exports: $Exports<'highcharts/js/modules/broken-axis'>;
}
declare module 'highcharts/js/modules/broken-axis.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/broken-axis.src'>;
}
declare module 'highcharts/js/modules/data.js' {
  declare module.exports: $Exports<'highcharts/js/modules/data'>;
}
declare module 'highcharts/js/modules/data.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/data.src'>;
}
declare module 'highcharts/js/modules/drilldown.js' {
  declare module.exports: $Exports<'highcharts/js/modules/drilldown'>;
}
declare module 'highcharts/js/modules/drilldown.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/drilldown.src'>;
}
declare module 'highcharts/js/modules/exporting.js' {
  declare module.exports: $Exports<'highcharts/js/modules/exporting'>;
}
declare module 'highcharts/js/modules/exporting.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/exporting.src'>;
}
declare module 'highcharts/js/modules/funnel.js' {
  declare module.exports: $Exports<'highcharts/js/modules/funnel'>;
}
declare module 'highcharts/js/modules/funnel.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/funnel.src'>;
}
declare module 'highcharts/js/modules/gantt.js' {
  declare module.exports: $Exports<'highcharts/js/modules/gantt'>;
}
declare module 'highcharts/js/modules/gantt.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/gantt.src'>;
}
declare module 'highcharts/js/modules/grid-axis.js' {
  declare module.exports: $Exports<'highcharts/js/modules/grid-axis'>;
}
declare module 'highcharts/js/modules/grid-axis.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/grid-axis.src'>;
}
declare module 'highcharts/js/modules/heatmap.js' {
  declare module.exports: $Exports<'highcharts/js/modules/heatmap'>;
}
declare module 'highcharts/js/modules/heatmap.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/heatmap.src'>;
}
declare module 'highcharts/js/modules/map.js' {
  declare module.exports: $Exports<'highcharts/js/modules/map'>;
}
declare module 'highcharts/js/modules/map.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/map.src'>;
}
declare module 'highcharts/js/modules/no-data-to-display.js' {
  declare module.exports: $Exports<'highcharts/js/modules/no-data-to-display'>;
}
declare module 'highcharts/js/modules/no-data-to-display.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/no-data-to-display.src'>;
}
declare module 'highcharts/js/modules/offline-exporting.js' {
  declare module.exports: $Exports<'highcharts/js/modules/offline-exporting'>;
}
declare module 'highcharts/js/modules/offline-exporting.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/offline-exporting.src'>;
}
declare module 'highcharts/js/modules/overlapping-datalabels.js' {
  declare module.exports: $Exports<'highcharts/js/modules/overlapping-datalabels'>;
}
declare module 'highcharts/js/modules/overlapping-datalabels.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/overlapping-datalabels.src'>;
}
declare module 'highcharts/js/modules/series-label.js' {
  declare module.exports: $Exports<'highcharts/js/modules/series-label'>;
}
declare module 'highcharts/js/modules/series-label.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/series-label.src'>;
}
declare module 'highcharts/js/modules/solid-gauge.js' {
  declare module.exports: $Exports<'highcharts/js/modules/solid-gauge'>;
}
declare module 'highcharts/js/modules/solid-gauge.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/solid-gauge.src'>;
}
declare module 'highcharts/js/modules/static-scale.js' {
  declare module.exports: $Exports<'highcharts/js/modules/static-scale'>;
}
declare module 'highcharts/js/modules/static-scale.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/static-scale.src'>;
}
declare module 'highcharts/js/modules/stock.js' {
  declare module.exports: $Exports<'highcharts/js/modules/stock'>;
}
declare module 'highcharts/js/modules/stock.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/stock.src'>;
}
declare module 'highcharts/js/modules/treemap.js' {
  declare module.exports: $Exports<'highcharts/js/modules/treemap'>;
}
declare module 'highcharts/js/modules/treemap.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/treemap.src'>;
}
declare module 'highcharts/js/modules/xrange-series.js' {
  declare module.exports: $Exports<'highcharts/js/modules/xrange-series'>;
}
declare module 'highcharts/js/modules/xrange-series.src.js' {
  declare module.exports: $Exports<'highcharts/js/modules/xrange-series.src'>;
}
declare module 'highcharts/js/themes/dark-blue.js' {
  declare module.exports: $Exports<'highcharts/js/themes/dark-blue'>;
}
declare module 'highcharts/js/themes/dark-green.js' {
  declare module.exports: $Exports<'highcharts/js/themes/dark-green'>;
}
declare module 'highcharts/js/themes/dark-unica.js' {
  declare module.exports: $Exports<'highcharts/js/themes/dark-unica'>;
}
declare module 'highcharts/js/themes/gray.js' {
  declare module.exports: $Exports<'highcharts/js/themes/gray'>;
}
declare module 'highcharts/js/themes/grid-light.js' {
  declare module.exports: $Exports<'highcharts/js/themes/grid-light'>;
}
declare module 'highcharts/js/themes/grid.js' {
  declare module.exports: $Exports<'highcharts/js/themes/grid'>;
}
declare module 'highcharts/js/themes/sand-signika.js' {
  declare module.exports: $Exports<'highcharts/js/themes/sand-signika'>;
}
declare module 'highcharts/js/themes/skies.js' {
  declare module.exports: $Exports<'highcharts/js/themes/skies'>;
}
declare module 'highcharts/lib/canvg.js' {
  declare module.exports: $Exports<'highcharts/lib/canvg'>;
}
declare module 'highcharts/lib/canvg.src.js' {
  declare module.exports: $Exports<'highcharts/lib/canvg.src'>;
}
declare module 'highcharts/lib/jspdf.js' {
  declare module.exports: $Exports<'highcharts/lib/jspdf'>;
}
declare module 'highcharts/lib/jspdf.src.js' {
  declare module.exports: $Exports<'highcharts/lib/jspdf.src'>;
}
declare module 'highcharts/lib/rgbcolor.js' {
  declare module.exports: $Exports<'highcharts/lib/rgbcolor'>;
}
declare module 'highcharts/lib/rgbcolor.src.js' {
  declare module.exports: $Exports<'highcharts/lib/rgbcolor.src'>;
}
declare module 'highcharts/lib/svg2pdf.js' {
  declare module.exports: $Exports<'highcharts/lib/svg2pdf'>;
}
declare module 'highcharts/lib/svg2pdf.src.js' {
  declare module.exports: $Exports<'highcharts/lib/svg2pdf.src'>;
}
declare module 'highcharts/modules/accessibility.js' {
  declare module.exports: $Exports<'highcharts/modules/accessibility'>;
}
declare module 'highcharts/modules/accessibility.src.js' {
  declare module.exports: $Exports<'highcharts/modules/accessibility.src'>;
}
declare module 'highcharts/modules/annotations.js' {
  declare module.exports: $Exports<'highcharts/modules/annotations'>;
}
declare module 'highcharts/modules/annotations.src.js' {
  declare module.exports: $Exports<'highcharts/modules/annotations.src'>;
}
declare module 'highcharts/modules/boost-canvas.js' {
  declare module.exports: $Exports<'highcharts/modules/boost-canvas'>;
}
declare module 'highcharts/modules/boost-canvas.src.js' {
  declare module.exports: $Exports<'highcharts/modules/boost-canvas.src'>;
}
declare module 'highcharts/modules/boost.js' {
  declare module.exports: $Exports<'highcharts/modules/boost'>;
}
declare module 'highcharts/modules/boost.src.js' {
  declare module.exports: $Exports<'highcharts/modules/boost.src'>;
}
declare module 'highcharts/modules/broken-axis.js' {
  declare module.exports: $Exports<'highcharts/modules/broken-axis'>;
}
declare module 'highcharts/modules/broken-axis.src.js' {
  declare module.exports: $Exports<'highcharts/modules/broken-axis.src'>;
}
declare module 'highcharts/modules/canvas-tools.js' {
  declare module.exports: $Exports<'highcharts/modules/canvas-tools'>;
}
declare module 'highcharts/modules/canvas-tools.src.js' {
  declare module.exports: $Exports<'highcharts/modules/canvas-tools.src'>;
}
declare module 'highcharts/modules/data.js' {
  declare module.exports: $Exports<'highcharts/modules/data'>;
}
declare module 'highcharts/modules/data.src.js' {
  declare module.exports: $Exports<'highcharts/modules/data.src'>;
}
declare module 'highcharts/modules/drilldown.js' {
  declare module.exports: $Exports<'highcharts/modules/drilldown'>;
}
declare module 'highcharts/modules/drilldown.src.js' {
  declare module.exports: $Exports<'highcharts/modules/drilldown.src'>;
}
declare module 'highcharts/modules/exporting.js' {
  declare module.exports: $Exports<'highcharts/modules/exporting'>;
}
declare module 'highcharts/modules/exporting.src.js' {
  declare module.exports: $Exports<'highcharts/modules/exporting.src'>;
}
declare module 'highcharts/modules/funnel.js' {
  declare module.exports: $Exports<'highcharts/modules/funnel'>;
}
declare module 'highcharts/modules/funnel.src.js' {
  declare module.exports: $Exports<'highcharts/modules/funnel.src'>;
}
declare module 'highcharts/modules/gantt.js' {
  declare module.exports: $Exports<'highcharts/modules/gantt'>;
}
declare module 'highcharts/modules/gantt.src.js' {
  declare module.exports: $Exports<'highcharts/modules/gantt.src'>;
}
declare module 'highcharts/modules/grid-axis.js' {
  declare module.exports: $Exports<'highcharts/modules/grid-axis'>;
}
declare module 'highcharts/modules/grid-axis.src.js' {
  declare module.exports: $Exports<'highcharts/modules/grid-axis.src'>;
}
declare module 'highcharts/modules/heatmap.js' {
  declare module.exports: $Exports<'highcharts/modules/heatmap'>;
}
declare module 'highcharts/modules/heatmap.src.js' {
  declare module.exports: $Exports<'highcharts/modules/heatmap.src'>;
}
declare module 'highcharts/modules/map.js' {
  declare module.exports: $Exports<'highcharts/modules/map'>;
}
declare module 'highcharts/modules/map.src.js' {
  declare module.exports: $Exports<'highcharts/modules/map.src'>;
}
declare module 'highcharts/modules/no-data-to-display.js' {
  declare module.exports: $Exports<'highcharts/modules/no-data-to-display'>;
}
declare module 'highcharts/modules/no-data-to-display.src.js' {
  declare module.exports: $Exports<'highcharts/modules/no-data-to-display.src'>;
}
declare module 'highcharts/modules/offline-exporting.js' {
  declare module.exports: $Exports<'highcharts/modules/offline-exporting'>;
}
declare module 'highcharts/modules/offline-exporting.src.js' {
  declare module.exports: $Exports<'highcharts/modules/offline-exporting.src'>;
}
declare module 'highcharts/modules/overlapping-datalabels.js' {
  declare module.exports: $Exports<'highcharts/modules/overlapping-datalabels'>;
}
declare module 'highcharts/modules/overlapping-datalabels.src.js' {
  declare module.exports: $Exports<'highcharts/modules/overlapping-datalabels.src'>;
}
declare module 'highcharts/modules/series-label.js' {
  declare module.exports: $Exports<'highcharts/modules/series-label'>;
}
declare module 'highcharts/modules/series-label.src.js' {
  declare module.exports: $Exports<'highcharts/modules/series-label.src'>;
}
declare module 'highcharts/modules/solid-gauge.js' {
  declare module.exports: $Exports<'highcharts/modules/solid-gauge'>;
}
declare module 'highcharts/modules/solid-gauge.src.js' {
  declare module.exports: $Exports<'highcharts/modules/solid-gauge.src'>;
}
declare module 'highcharts/modules/static-scale.js' {
  declare module.exports: $Exports<'highcharts/modules/static-scale'>;
}
declare module 'highcharts/modules/static-scale.src.js' {
  declare module.exports: $Exports<'highcharts/modules/static-scale.src'>;
}
declare module 'highcharts/modules/stock.js' {
  declare module.exports: $Exports<'highcharts/modules/stock'>;
}
declare module 'highcharts/modules/stock.src.js' {
  declare module.exports: $Exports<'highcharts/modules/stock.src'>;
}
declare module 'highcharts/modules/treemap.js' {
  declare module.exports: $Exports<'highcharts/modules/treemap'>;
}
declare module 'highcharts/modules/treemap.src.js' {
  declare module.exports: $Exports<'highcharts/modules/treemap.src'>;
}
declare module 'highcharts/modules/xrange-series.js' {
  declare module.exports: $Exports<'highcharts/modules/xrange-series'>;
}
declare module 'highcharts/modules/xrange-series.src.js' {
  declare module.exports: $Exports<'highcharts/modules/xrange-series.src'>;
}
declare module 'highcharts/themes/dark-blue.js' {
  declare module.exports: $Exports<'highcharts/themes/dark-blue'>;
}
declare module 'highcharts/themes/dark-green.js' {
  declare module.exports: $Exports<'highcharts/themes/dark-green'>;
}
declare module 'highcharts/themes/dark-unica.js' {
  declare module.exports: $Exports<'highcharts/themes/dark-unica'>;
}
declare module 'highcharts/themes/gray.js' {
  declare module.exports: $Exports<'highcharts/themes/gray'>;
}
declare module 'highcharts/themes/grid-light.js' {
  declare module.exports: $Exports<'highcharts/themes/grid-light'>;
}
declare module 'highcharts/themes/grid.js' {
  declare module.exports: $Exports<'highcharts/themes/grid'>;
}
declare module 'highcharts/themes/sand-signika.js' {
  declare module.exports: $Exports<'highcharts/themes/sand-signika'>;
}
declare module 'highcharts/themes/skies.js' {
  declare module.exports: $Exports<'highcharts/themes/skies'>;
}
