// flow-typed signature: c69ee257387bd7b32f517d126728f055
// flow-typed version: <<STUB>>/icheck_v^1.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'icheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'icheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'icheck/demo/js/custom.min' {
  declare module.exports: any;
}

declare module 'icheck/demo/js/jquery' {
  declare module.exports: any;
}

declare module 'icheck/demo/js/zepto' {
  declare module.exports: any;
}

declare module 'icheck/icheck' {
  declare module.exports: any;
}

declare module 'icheck/icheck.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'icheck/demo/js/custom.min.js' {
  declare module.exports: $Exports<'icheck/demo/js/custom.min'>;
}
declare module 'icheck/demo/js/jquery.js' {
  declare module.exports: $Exports<'icheck/demo/js/jquery'>;
}
declare module 'icheck/demo/js/zepto.js' {
  declare module.exports: $Exports<'icheck/demo/js/zepto'>;
}
declare module 'icheck/icheck.js' {
  declare module.exports: $Exports<'icheck/icheck'>;
}
declare module 'icheck/icheck.min.js' {
  declare module.exports: $Exports<'icheck/icheck.min'>;
}
