// flow-typed signature: bafa2dfd50b3a9d71ef6ba3fbda4bc76
// flow-typed version: <<STUB>>/jquery.scrollto_v^2.1.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery.scrollto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery.scrollto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery.scrollto/jquery.scrollTo' {
  declare module.exports: any;
}

declare module 'jquery.scrollto/jquery.scrollTo.min' {
  declare module.exports: any;
}

declare module 'jquery.scrollto/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery.scrollto/jquery.scrollTo.js' {
  declare module.exports: $Exports<'jquery.scrollto/jquery.scrollTo'>;
}
declare module 'jquery.scrollto/jquery.scrollTo.min.js' {
  declare module.exports: $Exports<'jquery.scrollto/jquery.scrollTo.min'>;
}
declare module 'jquery.scrollto/tests/test.js' {
  declare module.exports: $Exports<'jquery.scrollto/tests/test'>;
}
