// flow-typed signature: 4836983a4ea51ad6c5f61190d723d04a
// flow-typed version: <<STUB>>/jquery-visible_v^1.2.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-visible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-visible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-visible/benchmark/jquery-1.10.2.min' {
  declare module.exports: any;
}

declare module 'jquery-visible/jquery.visible' {
  declare module.exports: any;
}

declare module 'jquery-visible/jquery.visible.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-visible/benchmark/jquery-1.10.2.min.js' {
  declare module.exports: $Exports<'jquery-visible/benchmark/jquery-1.10.2.min'>;
}
declare module 'jquery-visible/jquery.visible.js' {
  declare module.exports: $Exports<'jquery-visible/jquery.visible'>;
}
declare module 'jquery-visible/jquery.visible.min.js' {
  declare module.exports: $Exports<'jquery-visible/jquery.visible.min'>;
}
