// flow-typed signature: be83cefdf4c5b7dce1030dca0e854469
// flow-typed version: <<STUB>>/promise-polyfill_v^6.0.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-polyfill/karma.conf' {
  declare module.exports: any;
}

declare module 'promise-polyfill/promise' {
  declare module.exports: any;
}

declare module 'promise-polyfill/promise.min' {
  declare module.exports: any;
}

declare module 'promise-polyfill/test/adapter' {
  declare module.exports: any;
}

declare module 'promise-polyfill/test/promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-polyfill/karma.conf.js' {
  declare module.exports: $Exports<'promise-polyfill/karma.conf'>;
}
declare module 'promise-polyfill/promise.js' {
  declare module.exports: $Exports<'promise-polyfill/promise'>;
}
declare module 'promise-polyfill/promise.min.js' {
  declare module.exports: $Exports<'promise-polyfill/promise.min'>;
}
declare module 'promise-polyfill/test/adapter.js' {
  declare module.exports: $Exports<'promise-polyfill/test/adapter'>;
}
declare module 'promise-polyfill/test/promise.js' {
  declare module.exports: $Exports<'promise-polyfill/test/promise'>;
}
