// flow-typed signature: 06abb2f2ebd2beeccc2907d60df598b5
// flow-typed version: <<STUB>>/react-social_v^1.9.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-social'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-social' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-social/react-social' {
  declare module.exports: any;
}

declare module 'react-social/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-social/react-social.js' {
  declare module.exports: $Exports<'react-social/react-social'>;
}
declare module 'react-social/test.js' {
  declare module.exports: $Exports<'react-social/test'>;
}
