// flow-typed signature: 2fa7d0ed4348771979ba548c052b8f01
// flow-typed version: <<STUB>>/react-facebook_v^4.0.16/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook/__tests__/share' {
  declare module.exports: any;
}

declare module 'react-facebook/gulpfile' {
  declare module.exports: any;
}

declare module 'react-facebook/jest/setup' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/index' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Like' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Login' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Page' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Process' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Share' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook/src/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook/src/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook/src/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook/src/index' {
  declare module.exports: any;
}

declare module 'react-facebook/src/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Like' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Login' {
  declare module.exports: any;
}

declare module 'react-facebook/src/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Page' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Process' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Share' {
  declare module.exports: any;
}

declare module 'react-facebook/src/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook/src/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook/src/utils/getCurrentHref' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook/__tests__/share.jsx' {
  declare module.exports: $Exports<'react-facebook/__tests__/share'>;
}
declare module 'react-facebook/gulpfile.js' {
  declare module.exports: $Exports<'react-facebook/gulpfile'>;
}
declare module 'react-facebook/jest/setup.js' {
  declare module.exports: $Exports<'react-facebook/jest/setup'>;
}
declare module 'react-facebook/lib/Comments.js' {
  declare module.exports: $Exports<'react-facebook/lib/Comments'>;
}
declare module 'react-facebook/lib/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook/lib/CommentsCount'>;
}
declare module 'react-facebook/lib/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/ColorScheme'>;
}
declare module 'react-facebook/lib/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/CommentsOrderBy'>;
}
declare module 'react-facebook/lib/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeAction'>;
}
declare module 'react-facebook/lib/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeLayout'>;
}
declare module 'react-facebook/lib/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeSize'>;
}
declare module 'react-facebook/lib/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook/lib/EmbeddedPost'>;
}
declare module 'react-facebook/lib/Facebook.js' {
  declare module.exports: $Exports<'react-facebook/lib/Facebook'>;
}
declare module 'react-facebook/lib/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook/lib/FacebookProvider'>;
}
declare module 'react-facebook/lib/Feed.js' {
  declare module.exports: $Exports<'react-facebook/lib/Feed'>;
}
declare module 'react-facebook/lib/index.js' {
  declare module.exports: $Exports<'react-facebook/lib/index'>;
}
declare module 'react-facebook/lib/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook/lib/InitFacebook'>;
}
declare module 'react-facebook/lib/Like.js' {
  declare module.exports: $Exports<'react-facebook/lib/Like'>;
}
declare module 'react-facebook/lib/Login.js' {
  declare module.exports: $Exports<'react-facebook/lib/Login'>;
}
declare module 'react-facebook/lib/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook/lib/LoginButton'>;
}
declare module 'react-facebook/lib/Page.js' {
  declare module.exports: $Exports<'react-facebook/lib/Page'>;
}
declare module 'react-facebook/lib/Parser.js' {
  declare module.exports: $Exports<'react-facebook/lib/Parser'>;
}
declare module 'react-facebook/lib/Process.js' {
  declare module.exports: $Exports<'react-facebook/lib/Process'>;
}
declare module 'react-facebook/lib/Share.js' {
  declare module.exports: $Exports<'react-facebook/lib/Share'>;
}
declare module 'react-facebook/lib/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook/lib/ShareButton'>;
}
declare module 'react-facebook/lib/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook/lib/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook/lib/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook/lib/utils/getCurrentHref'>;
}
declare module 'react-facebook/src/Comments.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Comments'>;
}
declare module 'react-facebook/src/CommentsCount.jsx' {
  declare module.exports: $Exports<'react-facebook/src/CommentsCount'>;
}
declare module 'react-facebook/src/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/ColorScheme'>;
}
declare module 'react-facebook/src/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/CommentsOrderBy'>;
}
declare module 'react-facebook/src/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/LikeAction'>;
}
declare module 'react-facebook/src/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/LikeLayout'>;
}
declare module 'react-facebook/src/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/LikeSize'>;
}
declare module 'react-facebook/src/EmbeddedPost.jsx' {
  declare module.exports: $Exports<'react-facebook/src/EmbeddedPost'>;
}
declare module 'react-facebook/src/Facebook.js' {
  declare module.exports: $Exports<'react-facebook/src/Facebook'>;
}
declare module 'react-facebook/src/FacebookProvider.jsx' {
  declare module.exports: $Exports<'react-facebook/src/FacebookProvider'>;
}
declare module 'react-facebook/src/Feed.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Feed'>;
}
declare module 'react-facebook/src/index.js' {
  declare module.exports: $Exports<'react-facebook/src/index'>;
}
declare module 'react-facebook/src/InitFacebook.jsx' {
  declare module.exports: $Exports<'react-facebook/src/InitFacebook'>;
}
declare module 'react-facebook/src/Like.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Like'>;
}
declare module 'react-facebook/src/Login.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Login'>;
}
declare module 'react-facebook/src/LoginButton.jsx' {
  declare module.exports: $Exports<'react-facebook/src/LoginButton'>;
}
declare module 'react-facebook/src/Page.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Page'>;
}
declare module 'react-facebook/src/Parser.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Parser'>;
}
declare module 'react-facebook/src/Process.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Process'>;
}
declare module 'react-facebook/src/Share.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Share'>;
}
declare module 'react-facebook/src/ShareButton.jsx' {
  declare module.exports: $Exports<'react-facebook/src/ShareButton'>;
}
declare module 'react-facebook/src/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook/src/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook/src/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook/src/utils/getCurrentHref'>;
}
