// flow-typed signature: b3a3aff360c759b1742abd6841d846a8
// flow-typed version: <<STUB>>/react-file-input_v^0.2.5/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-file-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-file-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-file-input/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-file-input/lib/index.js' {
  declare module.exports: $Exports<'react-file-input/lib/index'>;
}
