// flow-typed signature: f20ff5b1381468094af13976cfb3fbc2
// flow-typed version: <<STUB>>/react-dates_v^4.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dates/_gh-pages/static/manager.bundle' {
  declare module.exports: any;
}

declare module 'react-dates/_gh-pages/static/preview.bundle' {
  declare module.exports: any;
}

declare module 'react-dates/constants' {
  declare module.exports: any;
}

declare module 'react-dates/karma.conf' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/OutsideClickHandler' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isTouchDevice' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/toMomentObject' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/OutsideClickHandler' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isTouchDevice' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/toMomentObject' {
  declare module.exports: any;
}

declare module 'react-dates/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dates/_gh-pages/static/manager.bundle.js' {
  declare module.exports: $Exports<'react-dates/_gh-pages/static/manager.bundle'>;
}
declare module 'react-dates/_gh-pages/static/preview.bundle.js' {
  declare module.exports: $Exports<'react-dates/_gh-pages/static/preview.bundle'>;
}
declare module 'react-dates/constants.js' {
  declare module.exports: $Exports<'react-dates/constants'>;
}
declare module 'react-dates/index' {
  declare module.exports: $Exports<'react-dates'>;
}
declare module 'react-dates/index.js' {
  declare module.exports: $Exports<'react-dates'>;
}
declare module 'react-dates/karma.conf.js' {
  declare module.exports: $Exports<'react-dates/karma.conf'>;
}
declare module 'react-dates/lib/components/CalendarDay.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarDay'>;
}
declare module 'react-dates/lib/components/CalendarMonth.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarMonth'>;
}
declare module 'react-dates/lib/components/CalendarMonthGrid.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarMonthGrid'>;
}
declare module 'react-dates/lib/components/DateInput.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateInput'>;
}
declare module 'react-dates/lib/components/DateRangePicker.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateRangePicker'>;
}
declare module 'react-dates/lib/components/DateRangePickerInput.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateRangePickerInput'>;
}
declare module 'react-dates/lib/components/DateRangePickerInputController.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateRangePickerInputController'>;
}
declare module 'react-dates/lib/components/DayPicker.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPicker'>;
}
declare module 'react-dates/lib/components/DayPickerNavigation.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPickerNavigation'>;
}
declare module 'react-dates/lib/components/DayPickerRangeController.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPickerRangeController'>;
}
declare module 'react-dates/lib/components/OutsideClickHandler.js' {
  declare module.exports: $Exports<'react-dates/lib/components/OutsideClickHandler'>;
}
declare module 'react-dates/lib/components/SingleDatePicker.js' {
  declare module.exports: $Exports<'react-dates/lib/components/SingleDatePicker'>;
}
declare module 'react-dates/lib/components/SingleDatePickerInput.js' {
  declare module.exports: $Exports<'react-dates/lib/components/SingleDatePickerInput'>;
}
declare module 'react-dates/lib/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates/lib/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/DateRangePickerShape'>;
}
declare module 'react-dates/lib/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/FocusedInputShape'>;
}
declare module 'react-dates/lib/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/OrientationShape'>;
}
declare module 'react-dates/lib/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates/lib/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates/lib/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates/lib/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getTransformStyles'>;
}
declare module 'react-dates/lib/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates/lib/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates/lib/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isNextDay'>;
}
declare module 'react-dates/lib/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isSameDay'>;
}
declare module 'react-dates/lib/utils/isTouchDevice.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isTouchDevice'>;
}
declare module 'react-dates/lib/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isTransitionEndSupported'>;
}
declare module 'react-dates/lib/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/toISODateString'>;
}
declare module 'react-dates/lib/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/toLocalizedDateString'>;
}
declare module 'react-dates/lib/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/toMomentObject'>;
}
declare module 'react-dates/src/components/CalendarDay.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarDay'>;
}
declare module 'react-dates/src/components/CalendarMonth.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarMonth'>;
}
declare module 'react-dates/src/components/CalendarMonthGrid.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarMonthGrid'>;
}
declare module 'react-dates/src/components/DateInput.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateInput'>;
}
declare module 'react-dates/src/components/DateRangePicker.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateRangePicker'>;
}
declare module 'react-dates/src/components/DateRangePickerInput.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateRangePickerInput'>;
}
declare module 'react-dates/src/components/DateRangePickerInputController.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateRangePickerInputController'>;
}
declare module 'react-dates/src/components/DayPicker.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPicker'>;
}
declare module 'react-dates/src/components/DayPickerNavigation.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPickerNavigation'>;
}
declare module 'react-dates/src/components/DayPickerRangeController.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPickerRangeController'>;
}
declare module 'react-dates/src/components/OutsideClickHandler.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/OutsideClickHandler'>;
}
declare module 'react-dates/src/components/SingleDatePicker.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/SingleDatePicker'>;
}
declare module 'react-dates/src/components/SingleDatePickerInput.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/SingleDatePickerInput'>;
}
declare module 'react-dates/src/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates/src/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/DateRangePickerShape'>;
}
declare module 'react-dates/src/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/FocusedInputShape'>;
}
declare module 'react-dates/src/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/OrientationShape'>;
}
declare module 'react-dates/src/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates/src/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates/src/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates/src/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getTransformStyles'>;
}
declare module 'react-dates/src/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates/src/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates/src/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isNextDay'>;
}
declare module 'react-dates/src/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isSameDay'>;
}
declare module 'react-dates/src/utils/isTouchDevice.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isTouchDevice'>;
}
declare module 'react-dates/src/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isTransitionEndSupported'>;
}
declare module 'react-dates/src/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates/src/utils/toISODateString'>;
}
declare module 'react-dates/src/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates/src/utils/toLocalizedDateString'>;
}
declare module 'react-dates/src/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates/src/utils/toMomentObject'>;
}
declare module 'react-dates/webpack.config.js' {
  declare module.exports: $Exports<'react-dates/webpack.config'>;
}
