// flow-typed signature: adc47b4c7d88a332c27187500cf196c3
// flow-typed version: <<STUB>>/react-facebook-login_v^3.4.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook-login/demo/bundle' {
  declare module.exports: any;
}

declare module 'react-facebook-login/demo/index' {
  declare module.exports: any;
}

declare module 'react-facebook-login/dist/facebook-login' {
  declare module.exports: any;
}

declare module 'react-facebook-login/src/facebook' {
  declare module.exports: any;
}

declare module 'react-facebook-login/src/index' {
  declare module.exports: any;
}

declare module 'react-facebook-login/src/objectToParams' {
  declare module.exports: any;
}

declare module 'react-facebook-login/webpack.config.dist' {
  declare module.exports: any;
}

declare module 'react-facebook-login/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook-login/demo/bundle.js' {
  declare module.exports: $Exports<'react-facebook-login/demo/bundle'>;
}
declare module 'react-facebook-login/demo/index.js' {
  declare module.exports: $Exports<'react-facebook-login/demo/index'>;
}
declare module 'react-facebook-login/dist/facebook-login.js' {
  declare module.exports: $Exports<'react-facebook-login/dist/facebook-login'>;
}
declare module 'react-facebook-login/src/facebook.js' {
  declare module.exports: $Exports<'react-facebook-login/src/facebook'>;
}
declare module 'react-facebook-login/src/index.js' {
  declare module.exports: $Exports<'react-facebook-login/src/index'>;
}
declare module 'react-facebook-login/src/objectToParams.js' {
  declare module.exports: $Exports<'react-facebook-login/src/objectToParams'>;
}
declare module 'react-facebook-login/webpack.config.dist.js' {
  declare module.exports: $Exports<'react-facebook-login/webpack.config.dist'>;
}
declare module 'react-facebook-login/webpack.config.js' {
  declare module.exports: $Exports<'react-facebook-login/webpack.config'>;
}
