// flow-typed signature: 867d94a3f836ef49f878c8653b51518a
// flow-typed version: <<STUB>>/react-rangeslider_v^1.0.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rangeslider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rangeslider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rangeslider/lib/index' {
  declare module.exports: any;
}

declare module 'react-rangeslider/lib/Rangeslider' {
  declare module.exports: any;
}

declare module 'react-rangeslider/lib/umd/ReactRangeslider' {
  declare module.exports: any;
}

declare module 'react-rangeslider/lib/umd/ReactRangeslider.min' {
  declare module.exports: any;
}

declare module 'react-rangeslider/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rangeslider/lib/index.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/index'>;
}
declare module 'react-rangeslider/lib/Rangeslider.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/Rangeslider'>;
}
declare module 'react-rangeslider/lib/umd/ReactRangeslider.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/umd/ReactRangeslider'>;
}
declare module 'react-rangeslider/lib/umd/ReactRangeslider.min.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/umd/ReactRangeslider.min'>;
}
declare module 'react-rangeslider/lib/utils.js' {
  declare module.exports: $Exports<'react-rangeslider/lib/utils'>;
}
