// flow-typed signature: 7a09e70c296d0eabed8b210c59d93dc1
// flow-typed version: <<STUB>>/react-sanfona_v0.0.15/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sanfona'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sanfona' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sanfona/dist-modules/Accordion/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/Accordion/test' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/AccordionItem/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/AccordionItem/test' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/AccordionItemBody/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/AccordionItemTitle/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/Accordion/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/Accordion/test' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/AccordionItem/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/AccordionItem/test' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/AccordionItemBody/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/AccordionItemTitle/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/test/compiler' {
  declare module.exports: any;
}

declare module 'react-sanfona/webpack.config.dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sanfona/dist-modules/Accordion/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/Accordion/index'>;
}
declare module 'react-sanfona/dist-modules/Accordion/test.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/Accordion/test'>;
}
declare module 'react-sanfona/dist-modules/AccordionItem/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/AccordionItem/index'>;
}
declare module 'react-sanfona/dist-modules/AccordionItem/test.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/AccordionItem/test'>;
}
declare module 'react-sanfona/dist-modules/AccordionItemBody/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/AccordionItemBody/index'>;
}
declare module 'react-sanfona/dist-modules/AccordionItemTitle/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/AccordionItemTitle/index'>;
}
declare module 'react-sanfona/dist-modules/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/index'>;
}
declare module 'react-sanfona/src/Accordion/index.jsx' {
  declare module.exports: $Exports<'react-sanfona/src/Accordion/index'>;
}
declare module 'react-sanfona/src/Accordion/test.jsx' {
  declare module.exports: $Exports<'react-sanfona/src/Accordion/test'>;
}
declare module 'react-sanfona/src/AccordionItem/index.jsx' {
  declare module.exports: $Exports<'react-sanfona/src/AccordionItem/index'>;
}
declare module 'react-sanfona/src/AccordionItem/test.jsx' {
  declare module.exports: $Exports<'react-sanfona/src/AccordionItem/test'>;
}
declare module 'react-sanfona/src/AccordionItemBody/index.jsx' {
  declare module.exports: $Exports<'react-sanfona/src/AccordionItemBody/index'>;
}
declare module 'react-sanfona/src/AccordionItemTitle/index.jsx' {
  declare module.exports: $Exports<'react-sanfona/src/AccordionItemTitle/index'>;
}
declare module 'react-sanfona/src/index.js' {
  declare module.exports: $Exports<'react-sanfona/src/index'>;
}
declare module 'react-sanfona/test/compiler.js' {
  declare module.exports: $Exports<'react-sanfona/test/compiler'>;
}
declare module 'react-sanfona/webpack.config.dist.js' {
  declare module.exports: $Exports<'react-sanfona/webpack.config.dist'>;
}
