// flow-typed signature: 5729a539c6d07d2bf16141d6643d2170
// flow-typed version: <<STUB>>/react-addons-update_v^15.4.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-update/index' {
  declare module.exports: $Exports<'react-addons-update'>;
}
declare module 'react-addons-update/index.js' {
  declare module.exports: $Exports<'react-addons-update'>;
}
