// flow-typed signature: c26bc302ee5627d1cb3d4dace8cdc29b
// flow-typed version: <<STUB>>/react-confirm2_v^0.2.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-confirm2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-confirm2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-confirm2/demo/index' {
  declare module.exports: any;
}

declare module 'react-confirm2/devserver' {
  declare module.exports: any;
}

declare module 'react-confirm2/lib/index' {
  declare module.exports: any;
}

declare module 'react-confirm2/src/index' {
  declare module.exports: any;
}

declare module 'react-confirm2/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-confirm2/demo/index.js' {
  declare module.exports: $Exports<'react-confirm2/demo/index'>;
}
declare module 'react-confirm2/devserver.js' {
  declare module.exports: $Exports<'react-confirm2/devserver'>;
}
declare module 'react-confirm2/lib/index.js' {
  declare module.exports: $Exports<'react-confirm2/lib/index'>;
}
declare module 'react-confirm2/src/index.jsx' {
  declare module.exports: $Exports<'react-confirm2/src/index'>;
}
declare module 'react-confirm2/webpack.config.js' {
  declare module.exports: $Exports<'react-confirm2/webpack.config'>;
}
