// flow-typed signature: e0976a80b1e0ebf6726babd9c2165240
// flow-typed version: <<STUB>>/react-facebook-login_v^3.6.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook-login/dist/facebook-login' {
  declare module.exports: any;
}

declare module 'react-facebook-login/dist/facebook' {
  declare module.exports: any;
}

declare module 'react-facebook-login/dist/index' {
  declare module.exports: any;
}

declare module 'react-facebook-login/dist/objectToParams' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook-login/dist/facebook-login.js' {
  declare module.exports: $Exports<'react-facebook-login/dist/facebook-login'>;
}
declare module 'react-facebook-login/dist/facebook.js' {
  declare module.exports: $Exports<'react-facebook-login/dist/facebook'>;
}
declare module 'react-facebook-login/dist/index.js' {
  declare module.exports: $Exports<'react-facebook-login/dist/index'>;
}
declare module 'react-facebook-login/dist/objectToParams.js' {
  declare module.exports: $Exports<'react-facebook-login/dist/objectToParams'>;
}
