// flow-typed signature: 88826a5e958036887f3f36341fdf69c2
// flow-typed version: <<STUB>>/react-icheck_v^0.3.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-icheck/lib/Checkbox' {
  declare module.exports: any;
}

declare module 'react-icheck/lib/CheckboxGroup' {
  declare module.exports: any;
}

declare module 'react-icheck/lib/EnhancedSwitch' {
  declare module.exports: any;
}

declare module 'react-icheck/lib/index' {
  declare module.exports: any;
}

declare module 'react-icheck/lib/Radio' {
  declare module.exports: any;
}

declare module 'react-icheck/lib/RadioGroup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-icheck/lib/Checkbox.js' {
  declare module.exports: $Exports<'react-icheck/lib/Checkbox'>;
}
declare module 'react-icheck/lib/CheckboxGroup.js' {
  declare module.exports: $Exports<'react-icheck/lib/CheckboxGroup'>;
}
declare module 'react-icheck/lib/EnhancedSwitch.js' {
  declare module.exports: $Exports<'react-icheck/lib/EnhancedSwitch'>;
}
declare module 'react-icheck/lib/index.js' {
  declare module.exports: $Exports<'react-icheck/lib/index'>;
}
declare module 'react-icheck/lib/Radio.js' {
  declare module.exports: $Exports<'react-icheck/lib/Radio'>;
}
declare module 'react-icheck/lib/RadioGroup.js' {
  declare module.exports: $Exports<'react-icheck/lib/RadioGroup'>;
}
