// flow-typed signature: 33ee3adad5c8ee53949446da94e2eb5c
// flow-typed version: <<STUB>>/slick-carousel_v^1.6.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slick-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slick-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slick-carousel/slick/slick' {
  declare module.exports: any;
}

declare module 'slick-carousel/slick/slick.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slick-carousel/slick/slick.js' {
  declare module.exports: $Exports<'slick-carousel/slick/slick'>;
}
declare module 'slick-carousel/slick/slick.min.js' {
  declare module.exports: $Exports<'slick-carousel/slick/slick.min'>;
}
