// flow-typed signature: 065846ec9cd2ca0240f06a49be38d662
// flow-typed version: <<STUB>>/vhost_v^3.0.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vhost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vhost' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vhost/index' {
  declare module.exports: $Exports<'vhost'>;
}
declare module 'vhost/index.js' {
  declare module.exports: $Exports<'vhost'>;
}
