import React, { PropTypes } from 'react'
import { connect } from 'react-redux'
import { Modal, Button } from 'react-bootstrap'
import { LinkContainer } from 'react-router-bootstrap'
import ModuleGrid from 'containers/ModuleGrid'
import PageGrid from 'containers/PageGrid'
import AppCreateForm from 'containers/AppCreateForm'

const AppDeleteModal = ({ show, app, cancel, proceed }) => (
  <Modal show={show}>
    <Modal.Header>
      <Modal.Title>Delete App</Modal.Title>
    </Modal.Header>

    <Modal.Body>
      <div className="text-center">
        <h4>
          <b>Warning: This cannot be undone</b>
        </h4>
        <h3>
          You're about to delete the following App: <br />
          <b>{app.title}</b>
        </h3>
      </div>
      <h5>By doing so, you will:</h5>
      <div className="checkbox">
        <label>
          <input type="checkbox" />
          Lose all of this app's users data and stats
        </label>
      </div>
      <div className="checkbox">
        <label>
          <input type="checkbox" />
          Lose all this app's content, both generated by you and its users
        </label>
      </div>
    </Modal.Body>

    <Modal.Footer>
      <Button onClick={() => cancel()}>Cancel, keep the app</Button>
      <Button bsStyle="danger" onClick={() => proceed(app.checksum)}>
        Delete this app
      </Button>
    </Modal.Footer>
  </Modal>
)

export default AppDeleteModal
